/* Tuner topic pool. Each entry is one spinnable Substack prompt.
   Grouped by strand only for authoring sanity — the spinner flattens them. */

const TOPICS = [

/* ---------- making & shipping ---------- */
"The project you abandoned at ninety percent, and what the last ten percent was really asking of you",
"What a deadline does that motivation cannot",
"The difference between a dead project and a paused one",
"Why rewriting is cheaper than deciding",
"The thing you built that nobody asked for and you use every day",
"Your most-used tool is forty lines long. Why the small thing beat the ambitious one",
"Shipping something you know is not finished",
"The feature you cut that nobody missed",
"What you learned from the version nobody saw",
"Building for an audience of one",
"The first user who was not you",
"When perfectionism is just fear wearing a nicer outfit",
"The bug that taught you more than the feature",
"Why you keep starting instead of finishing",
"The project you are embarrassed by and should not be",
"What your unfinished folder says about you",
"Working on something for a year before anyone noticed",
"The moment a side project became real",
"Killing something you loved because it was not working",
"How you decide what to build next",
"The difference between hard and tedious, and why you avoid the wrong one",
"What you would build if nobody could see it",
"Copying something exactly as a way to learn it",
"The tutorial you followed versus the thing you built badly on your own",
"Why the second version is always worse before it is better",
"The constraint that made the work better",
"Working with the wrong tool on purpose",
"What breaks when a project gets its tenth user",
"The demo that worked and the product that did not",
"Naming things: why it takes longer than building them",
"The prototype you should have thrown away",
"When to rebuild from scratch, and how you know",
"The maintenance nobody warned you about",
"Why the boring part is the product",
"Documentation as a form of thinking",
"The thing you automated that you should have just done twice",
"What you keep in a scratch file",
"Working on something with no idea if it will work",
"The moment you realized the idea was not the hard part",
"Why you ship on Fridays, or refuse to",
"Reading your own code from a year ago",
"The library you almost wrote before you found it",
"Choosing boring technology on purpose",
"The feature request that changed how you saw the product",
"Building the thing you wish existed and finding out why it does not",
"What happens when the fun part ends",
"The project that was really about avoiding another project",
"Working in public before it is good",
"The version number that meant something to nobody but you",
"How you decide something is done",
"Why every estimate you make is wrong in the same direction",
"The task you have moved to tomorrow eleven times",
"What a launch actually feels like",
"The silence after you ship",
"Making something that only works on your machine",
"Why you build the settings page last",
"The thing you learned by breaking production",
"What you would tell yourself before the first project",
"Building alone versus building with one other person",
"The collaborator who made you better and the one who made you slower",
"When to ask for help and why you waited too long",
"The code review that stung and was right",
"Why you defend decisions you no longer believe in",
"The feature you added because a competitor had it",
"Building for a user you have never met",
"What you assume about people who use your work",
"The support message that changed the roadmap",
"Why nobody reads the onboarding you wrote",
"Designing for the person who is in a hurry",
"The metric you optimized that made the product worse",
"What you stopped measuring, and what improved",
"Why the dashboard did not help",
"Building something that works offline",
"The thing that only breaks at 2am",
"What reliability actually costs",
"The trade-off you make every time without noticing",
"Speed versus correctness, told through one specific decision",
"Why you cache things you should just make fast",
"The system that got too clever",
"Simplicity as a discipline, not a style",
"What you deleted that made everything better",
"The abstraction you introduced too early",
"Copy and paste three times before you refactor: does the rule hold",
"When duplication is honest",
"The convention you follow that you cannot justify",
"Style guides as a way to stop arguing",
"The pull request that took a week to review",
"Why small changes are easier to trust",
"What continuous means when nobody is watching",
"Testing the thing you are most afraid of",
"The test that gave you false confidence",
"Why you write tests after, and whether that is defensible",
"The refactor that was worth it",
"The refactor that was not",
"Legacy code as somebody's best effort under pressure",
"Inheriting a codebase and the archaeology that follows",
"What good comments actually explain",
"The README as a promise",
"Open sourcing something and what you learned from the first issue",
"The contributor who improved your project and disappeared",
"Licensing, credit, and the ethics of building on other people's work",
"Why you stopped using the framework everyone recommended",
"The stack you would choose again",

/* ---------- AI & tools ---------- */
"What you stopped learning when you started using AI",
"The skill you handed over and want back",
"Why the prompt became the product",
"AI made you faster at the wrong things",
"Reading code you did not write, that you shipped",
"The agent that only works when you are watching",
"Giving software permission to speak as you",
"The moment a model was confidently, plausibly wrong",
"How you check work you cannot fully verify",
"What you refuse to delegate to a machine",
"The task you thought was creative until it was automated",
"Where AI is genuinely better than you, honestly stated",
"Why every AI-generated interface looks the same",
"The tells you use to spot generated writing",
"What taste means when execution is cheap",
"The new bottleneck: knowing what is worth making",
"Using AI to learn versus using it to skip learning",
"Explaining your work to a model and understanding it better",
"The conversation with a model that changed your mind",
"When the tool is confident and you are not",
"What it feels like to be the slowest part of your own workflow",
"The job you thought was safe",
"Talking to people who are frightened of this, without dismissing them",
"The energy, water, and labor behind the thing you use casually",
"Whose work trained the tool you rely on",
"Attribution when everything is remixed",
"The line between assistance and authorship",
"Publishing something a model largely wrote",
"Why you disclose, or why you do not",
"The essay you did not write because a model wrote a worse one first",
"What originality means now",
"Automating a person's job, including your own",
"The workflow you rebuilt three times this year",
"Tool switching as procrastination",
"Why your note system keeps collapsing",
"The app you paid for and used twice",
"Building your own tool instead of buying one",
"What a good default is worth",
"The keyboard shortcut that saved you a hundred hours",
"Why your terminal looks the way it does",
"Configuration as self-portrait",
"The setting you changed that changed your behavior",
"Notifications: what you turned off and what happened",
"The device you stopped carrying",
"What your home screen says about your priorities",
"Digital hoarding and the tabs you will never read",
"Search as a memory prosthetic",
"The file you cannot find and the system that failed you",
"Naming conventions as future kindness",
"Backups, and the loss that taught you",
"The password manager conversation you keep having with family",
"Privacy decisions you make for other people",
"What you would not put in a cloud",
"The permission you granted without reading",
"Terms of service as fiction",
"What an account deletion actually does",
"Owning your archive",
"Why you self-host something inconvenient",
"The service that shut down and took your work with it",
"Building for a platform that can change the rules",
"Writing somewhere you cannot be deplatformed",
"The API that broke your product overnight",
"Depending on a company that does not know you exist",
"What open means in practice",
"Reading the source of something you use daily",
"The bug report you filed that got fixed",
"Contributing to something bigger than your own work",
"How you decide a tool is trustworthy",
"The update that made something worse",
"Software that got heavier every year",
"Why old software still works and new software does not",
"Speed as a feature people feel but cannot name",
"The website that loads instantly and what it taught you",
"Accessibility as a design constraint that improves everything",
"Building for someone using a screen reader",
"The interface you could not use one-handed",
"Designing for a bad connection",
"What you assume about your user's device",
"The default that excluded someone",
"Localization and the assumptions inside your copy",
"Time zones as a humility lesson",
"The date format argument and why it matters",
"Units, currencies, and other quiet assumptions",
"Writing error messages that respect the reader",
"The empty state as a first impression",
"Loading states and the honesty of a progress bar",
"Undo as the most generous feature",
"Confirmation dialogs and the illusion of safety",
"The destructive action you made too easy",
"Designing for the tired user",
"What your product does at 3am",
"The feature only power users find",
"Keyboard-first software and who it leaves behind",
"Why you still use a text file for the important thing",
"Plain text as a bet on the future",
"The format you chose that outlived the app",
"Exporting your data and finding out what you actually own",
"The migration that took a weekend and a year of nerve",
"Version control for things that are not code",
"What software taught you about writing",
"What writing taught you about software",

/* ---------- internet, audience & attention ---------- */
"Big numbers and a quiet inbox: reach versus relationships",
"The post that did well and changed nothing",
"The post that did badly and changed everything",
"What you stopped posting and why",
"Writing for strangers versus writing for twelve people",
"The comment that stayed with you",
"Blocking someone and what it revealed",
"The account you follow that makes you worse",
"An honest audit of what you consume",
"The feed you left and what you missed",
"Why you keep an app you dislike",
"The scroll you cannot account for",
"Attention as the thing you actually spend",
"Being early to something and what it bought you",
"Getting a platform's algorithm right by accident",
"Optimizing for a machine and losing the reader",
"The headline you regret",
"Writing a title that is true and still gets read",
"Clickbait you fell for and what it taught you",
"The thing you shared without reading",
"Being wrong publicly and correcting it",
"The correction nobody saw",
"Deleting a post versus letting it stand",
"Your oldest post online and whether you still agree with it",
"Growing up in public",
"The internet's memory versus your own",
"Anonymity, pseudonymity, and what each frees you to say",
"The thing you would only write under a different name",
"Writing about people who can read it",
"Permission, consent, and telling shared stories",
"What you owe the people in your essays",
"The detail you changed to protect someone",
"When honesty becomes exposure",
"Vulnerability as a strategy and why it curdles",
"The post that was too raw to publish",
"Waiting a year before writing about something",
"Distance as a writing tool",
"The essay you can only write after it stops hurting",
"Journaling versus publishing",
"Why you write at all",
"The reader you imagine while writing",
"Publishing on a schedule versus when it is ready",
"Consistency, and what it costs in quality",
"The newsletter you unsubscribed from and why",
"What makes you open an email from a stranger",
"The subject line as a promise",
"Paywalls and what you actually owe subscribers",
"Charging for writing for the first time",
"The reader who paid and what changed",
"Free work as protection from a verdict",
"Audience capture: writing what your readers already believe",
"The opinion you softened and should not have",
"Changing your mind in front of an audience",
"The take you no longer hold",
"Arguing in good faith with someone who is not",
"When to engage and when to close the tab",
"The pile-on you watched and did not join",
"Context collapse: one message, five audiences",
"Writing for people who will read it out of context",
"Screenshots as permanent record",
"The group chat as the last honest place online",
"Small internets and why they feel better",
"Forums, and what we lost when they died",
"The community that raised you online",
"Lurking as a legitimate way to participate",
"Your first internet friend",
"Meeting an online friend in person",
"Parasocial relationships from both sides",
"The creator you outgrew",
"What you learned by unfollowing everyone",
"Curating a feed like a diet",
"Reading long things again, deliberately",
"The book you finished after a year of not finishing books",
"Attention span as a muscle or a myth",
"Boredom and what it is for",
"The walk without headphones",
"Doing one thing at a time as a radical act",
"The phone in another room experiment",
"Trying to be unreachable for a day",
"Being reachable as a job requirement",
"The email you took three weeks to answer",
"Inbox zero and the people it does not serve",
"Auto-replies as boundaries",
"Saying no in writing",
"The DM you did not send",
"Cold outreach: the real reply rate",
"The message that worked and why",
"Networking without the word networking",
"Asking a stranger for something",
"The favor you were granted and never repaid",
"Introductions as currency",
"The person who vouched for you",
"Being vouched for before you were ready",
"Referral, luck, and the myth of the meritocratic inbox",
"What a warm introduction actually is",
"Building a reputation you have to keep",
"The gap between how you are perceived and what you do",
"Personal brand as a cage",
"Retiring an identity you built online",
"Starting over on a new platform",
"The account you deleted and do not miss",
"Writing offline first",

/* ---------- work, money & ambition ---------- */
"Charging for something for the first time",
"The price you were too scared to say out loud",
"Raising your rate and losing a client you were glad to lose",
"The work you did for free that paid off, and the work that did not",
"Being underpaid and knowing it",
"Talking about money with a friend",
"What your parents taught you about money without saying it",
"The first thing you saved for",
"The purchase you still think about",
"Buying quality once versus cheap three times",
"The subscription audit nobody wants to do",
"What you spend on convenience",
"Time versus money at different points in your life",
"The job you took for the wrong reason",
"Quitting before you had the next thing",
"The interview that told you everything about the company",
"Questions you now ask in interviews",
"The offer you turned down",
"Negotiating when you have no leverage",
"What a title is actually worth",
"Being the youngest person in the room",
"Being the least experienced and most useful",
"Imposter feelings versus being genuinely new",
"The mentor who did not know they were one",
"Advice you were given that only works if you are already good",
"The advice you give that you do not follow",
"Survivor stories and the first mile nobody remembers",
"Luck, timing, and the story we tell instead",
"The opportunity you got because you were in a room",
"How you got into the room",
"Ambition as an inherited script",
"What you want versus what you were trained to want",
"The goal you achieved that felt like nothing",
"Moving the goalposts on yourself",
"Enough, defined concretely",
"The number that would change your decisions",
"Financial independence as a fantasy of control",
"Retirement, if the work is the point",
"Work you would do unpaid, and whether that is a trap",
"The hobby you monetized and ruined",
"Keeping one thing amateur on purpose",
"Craft versus career",
"The résumé line that is a lie by omission",
"Explaining a gap year, a failure, or a detour",
"The failure you learned nothing from",
"Post-mortems and the ones you skipped",
"Firing yourself from a role you were bad at",
"Delegating something you were proud of",
"The first person you managed",
"Telling someone no",
"Giving feedback that lands",
"Receiving feedback badly, in detail",
"The performance review that was accurate",
"Being managed well, once",
"The meeting that should have been a message",
"Meetings you protect and the ones you cancel",
"Calendars as a statement of values",
"Saying yes too fast",
"The commitment you honored past its usefulness",
"Sunk cost in a relationship, a project, or a career",
"The exit you planned for and the one you did not",
"Non-competes, NDAs, and what you cannot write about",
"Building something on company time",
"Side projects and the ethics of your best hours",
"What you owe an employer",
"What an employer owes you",
"Layoffs, from the inside",
"Watching a company change after it grew",
"The startup that was a family until it was not",
"Equity explained honestly to someone who has never had it",
"Fundraising as storytelling",
"The investor question you could not answer",
"Bootstrapping and the freedom you paid for",
"Revenue as the only real validation",
"The first sale",
"Customers who are wrong and customers who are right",
"Firing a customer",
"Pricing as positioning",
"Discounts and what they teach a buyer",
"Free tiers and the cost of a user who will never pay",
"The competitor you learned the most from",
"Copying versus being inspired, with a real example",
"Being copied",
"Moats, and whether you have one",
"The market you thought existed",
"Talking to twenty people before building anything",
"The interview question that revealed the real problem",
"Building the wrong thing well",
"Pivoting without calling it a pivot",
"Shutting something down cleanly",
"The email you sent to users when it ended",
"What you kept from a company that failed",
"Working for yourself and the loneliness nobody mentions",
"Structure when nobody imposes it",
"The morning routine that is actually a control ritual",
"Productivity systems as procrastination with a nicer name",
"What you do on a day with no meetings",
"Rest as part of the work",
"Burnout, described precisely, without metaphor",
"Coming back from burnout slowly",
"The vacation where you could not stop working",
"Work as identity and what happens when it stops",

/* ---------- learning & school ---------- */
"School and the internet teach opposite lessons",
"Grades as a lagging indicator",
"The class you hated that shaped you",
"The teacher who saw something first",
"Learning something because a person made it interesting",
"The subject you were told you were bad at",
"Being fast versus being deep",
"Cramming and what it does to memory",
"The exam you aced and cannot explain",
"Studying for the test versus studying the thing",
"Homework as compliance training",
"What you would keep from school if you could keep one thing",
"The extracurricular that was really about admissions",
"Doing things for a résumé and knowing it",
"The four-year plan you made and its hidden assumptions",
"Planning for a world that keeps moving",
"Choosing a major for the wrong reasons",
"The college conversation with your parents",
"Rankings and what they actually measure",
"The applicant you are on paper versus the person",
"Writing about yourself for someone who decides your future",
"Rejection letters and what they are worth",
"The waitlist as a lesson in uncertainty",
"Peers as the real curriculum",
"Learning more from a friend than a course",
"The study group that worked",
"Teaching something to understand it",
"Explaining your field to a twelve-year-old",
"The concept you thought you understood until you taught it",
"Reading a textbook cover to cover",
"Lectures versus documentation",
"Learning by breaking things",
"The first thing you learned entirely online",
"Free courses you did not finish",
"Certificates and their real signal value",
"Credentials versus portfolio",
"The interview where your projects mattered more than your transcript",
"Self-teaching and its blind spots",
"What a curriculum gives you that curiosity does not",
"The gap in your knowledge you keep working around",
"Fundamentals you skipped and had to return to",
"Learning math again as an adult",
"The language you started and abandoned",
"Fluency versus competence",
"Studying abroad in your head",
"The book that changed how you think",
"Rereading a book you loved at a different age",
"Books you pretend to have read",
"Note-taking systems and whether any of them help",
"Highlighting as a comfort activity",
"Retrieval practice, honestly evaluated",
"Spaced repetition and the things you chose to memorize",
"What is worth memorizing in an era of instant lookup",
"Knowing something versus being able to find it",
"The fact you were sure about and were wrong about",
"Updating a belief in public",
"Sources, and how you decide what to trust",
"Reading the primary source",
"Citation as intellectual honesty",
"The paper you read that everyone cites and nobody reads",
"Peer review explained to a skeptic",
"Replication and what it means for advice",
"Statistics you misused",
"Correlation stories you tell yourself",
"Anecdote as evidence, and when it is enough",
"Changing your mind about something you argued for",
"Steelmanning the position you dislike",
"The debate you lost and learned from",
"Being taught by someone younger",
"Learning from someone you disagree with",
"The apprenticeship you wish existed in your field",
"Watching an expert work",
"Deliberate practice versus repetition",
"Plateaus and how you got off one",
"The skill that took ten times longer than expected",
"Quitting a skill and being fine with it",
"The instrument you stopped playing",
"Returning to something after years away",
"Muscle memory as a kind of knowledge",
"Learning in your body versus in your head",
"The thing you can do but cannot explain",
"Tacit knowledge and how it gets transmitted",
"Apprentices, mentors, and the myth of self-made",
"What you learned from a job you disliked",
"Customer service as an education",
"Manual labor and what it taught you about software",
"The summer that changed what you wanted",
"Being bored as a child and what it built",
"Unstructured time for kids, argued honestly",
"What you would teach a thirteen-year-old with these tools",
"The trap a beginner falls into now that did not exist before",
"Tools first versus problems first",
"Learning to search well",
"Reading documentation as a skill",
"Debugging as the actual subject",
"Failure logs and what they reveal over a year",
"Keeping a record of what you did not know",
"The question you were too embarrassed to ask",
"Asking a basic question in a room of experts",
"Teaching a parent something technical",
"The knowledge gap inside your own family",

/* ---------- people, friendship & family ---------- */
"The friend you stopped talking to for no reason",
"Maintaining a friendship across time zones",
"The group chat that has outlived its group",
"Friendships that end without an ending",
"Making friends as an adult",
"The friend you outgrew and still love",
"Being the person who always organizes",
"Being the person who never texts first",
"Reaching out after a long silence",
"The message you should have sent",
"Apologizing properly",
"Being forgiven and not feeling it",
"Forgiving someone who never asked",
"The grudge you are still carrying",
"Conflict avoidance and what it costs",
"The conversation you rehearsed for weeks",
"Saying the hard thing kindly",
"Being told a hard truth and hearing it",
"The friend who told you what nobody else would",
"Loyalty versus honesty",
"Keeping a secret that is not yours",
"The advice you gave that went badly",
"Being asked for advice you are not qualified to give",
"Listening without fixing",
"The comfort that actually helped",
"Sitting with someone in a bad week",
"Showing up when it is inconvenient",
"Small gestures with disproportionate weight",
"The person who remembered something you mentioned once",
"Being remembered",
"Gift-giving and what it says",
"The thank-you note you never sent",
"Gratitude that is specific instead of general",
"Your parents as people with their own histories",
"The story about your family you only recently understood",
"What your grandparents did that you cannot imagine doing",
"Family recipes as documents",
"The thing your parent gave up",
"Learning your parent's fears",
"Becoming the adult in a family conversation",
"Caring for someone who used to care for you",
"Siblings and the different childhoods you had in the same house",
"Being the oldest, youngest, or only",
"Family expectations you inherited without agreeing to",
"Disagreeing with your family politically",
"Holidays and the labor behind them",
"The family tradition you will keep",
"The one you will not",
"Leaving home and what you took",
"Homesickness for a place or a version of yourself",
"Calling home more or less than you should",
"The phone call you keep meaning to make",
"Distance and the relationships that survive it",
"Moving away from a best friend",
"Long-distance anything",
"The person you think about who does not think about you",
"Unrequited in any form",
"Being liked by someone you do not like back",
"Rejecting someone kindly",
"The crush that shaped a year",
"First love, described without nostalgia",
"Breakups and the practical logistics nobody writes about",
"Splitting friends after an ending",
"Being single by choice and the questions you get",
"Dating apps as a design problem",
"Chemistry versus compatibility",
"The relationship that ended because of timing",
"Staying too long",
"Leaving too early",
"What a good partnership actually looks like day to day",
"Arguments you keep having",
"Learning someone else's love language and forgetting your own",
"Domestic labor and who notices it",
"Money in a relationship",
"Meeting the parents",
"Being someone's emergency contact",
"Chosen family",
"The mentor who became a friend",
"Friendships with a big age gap",
"The neighbor you actually know",
"Community as a practice, not a feeling",
"Volunteering and the honest reasons you did",
"The stranger who helped you",
"Helping a stranger and never knowing the outcome",
"Being on the receiving end of charity",
"Asking for help as a skill",
"The favor that changed your year",
"Reciprocity and keeping score",
"Introverts, extroverts, and the questions that framework fails to answer",
"Loneliness in a crowded life",
"Being alone versus being lonely",
"The friend you can be quiet with",
"Small talk and its underrated function",
"Learning names properly",
"Being new somewhere",
"The first week in a new city, socially",
"Third places and where yours went",
"Hosting badly and doing it anyway",
"Dinner parties on no budget",
"The recurring hangout that keeps a friendship alive",
"Grief, and the friends who stayed",
"Writing about someone who died",
"The voicemail you kept",

/* ---------- taste, art & design ---------- */
"Taste is a list of things you refuse to do",
"The five rules you will not break in your work",
"The rule you broke on purpose and were right to",
"How your taste changed in a year",
"Liking something you know is bad",
"Defending a guilty pleasure without the guilt",
"The critic who made you see something new",
"Reviews you read after you already decided",
"The album that scored a specific period of your life",
"A song you cannot listen to anymore",
"Listening to one album for a month",
"Shuffle versus sequence",
"The concert that ruined other concerts",
"Live music and the part recordings cannot hold",
"Learning an instrument as an adult",
"Playing badly in front of people",
"The film you have seen ten times",
"A movie you loved at fifteen and rewatched later",
"Watching something with subtitles on and why",
"Rewatching as a form of rest",
"The show you quit halfway and why",
"Endings that earned it",
"Spoilers and what they actually spoil",
"The book you could not finish and should have",
"Reading slowly on purpose",
"Marginalia and what you write in books",
"Lending a book and losing it",
"Physical media in a streaming world",
"The playlist as a letter",
"Making something for one person",
"The birthday gift you made",
"Handwriting versus typing",
"Letters, and who still writes them",
"The zine, the pamphlet, the small circulation",
"Print as a constraint that improves writing",
"Typography as an opinion",
"Choosing a typeface for a specific reason",
"The two-typeface rule and when you break it",
"Color as a decision, not a preference",
"Why most palettes look the same right now",
"Designing in black and white first",
"Whitespace as confidence",
"Grid systems and when to break them",
"The layout you copied and learned from",
"Motion that clarifies versus motion that decorates",
"The animation nobody notices, which is the point",
"Micro-interactions worth an evening",
"Skeuomorphism, flat design, and the pendulum",
"Nostalgia in interface design",
"Old software that still feels good",
"The physical object with a perfect interface",
"Buttons, switches, and the pleasure of mechanism",
"Products designed to last",
"Repair as a relationship with an object",
"The thing you have owned for ten years",
"Buying used on purpose",
"The maker whose work you keep",
"Craft in a mass-produced world",
"The handmade thing that is worse and better",
"Imperfection as evidence of a person",
"Signature and style: what is yours",
"Finding a voice versus performing one",
"Writing sentences you would say out loud",
"Reading your work aloud and what it exposes",
"Editing as the real writing",
"Cutting your favorite paragraph",
"The draft that was better before you fixed it",
"First lines and how you find them",
"Endings you cannot land",
"Structure as an argument",
"Writing short as a discipline",
"Long-form and why it still works",
"The essay that took a year",
"Publishing something imperfect on a deadline",
"Titles, and how much they carry",
"Metaphors that do too much work",
"Jargon and who it excludes",
"Explaining your work without jargon",
"Clarity as respect",
"Being interesting versus being clear",
"Humor in serious writing",
"The joke that carried an argument",
"Sincerity after a decade of irony",
"Earnestness as a risk",
"Writing about something everyone has written about",
"The overdone topic you have a real angle on",
"Contrarianism as a habit and its cost",
"Agreeing with the consensus in public",
"Nuance in a format that punishes it",
"Being quoted out of context",
"Writing something you cannot summarize",
"Photographs you take that nobody sees",
"The camera you actually use",
"Documenting a year in a specific way",
"Taking fewer pictures on purpose",
"The photo you did not take",
"Looking at art without knowing anything about it",
"The museum room you sat in",
"Public art in your city",
"Architecture you walk past daily",
"Learning to look at buildings",

/* ---------- body, health & habit ---------- */
"Sport taught you to lose on purpose",
"The point you gave up to win the game",
"Practice with no scoreboard",
"The hour before practice is the whole day",
"Training when you do not want to",
"The injury that changed how you move",
"Rehab as a lesson in patience",
"Coming back slower than you left",
"Comparing yourself to your own best year",
"Getting older in a sport",
"The coach who was right and harsh",
"The coach who was kind and effective",
"Being coached versus being told",
"Team sports and the version of you that shows up",
"Individual sports and the conversation in your head",
"Losing badly in public",
"Winning and feeling nothing",
"The rival who made you better",
"Sportsmanship in a specific moment",
"Watching a sport you cannot play",
"The athlete whose career you followed",
"Retirement in sport, at any age",
"Sleep as a build step",
"Everything you have reverted was written after eleven",
"The night you did not sleep and the day that followed",
"Sleep tracking and what it did to your sleep",
"Caffeine, honestly accounted for",
"The drink you gave up",
"Alcohol and the social architecture around it",
"Choosing not to drink in a drinking culture",
"Food as routine versus food as pleasure",
"Cooking the same thing every week",
"Learning one dish properly",
"Eating alone",
"The meal you cook for other people",
"Grocery shopping as a practice",
"Diet advice and the industry behind it",
"Tracking what you eat and stopping",
"Body image, written carefully",
"What exercise is actually for",
"Movement without a goal",
"Walking as thinking",
"The route you walk every day",
"Running and the first mile problem",
"Lifting as a legible progress system",
"Progress that stops being visible",
"Consistency over intensity, tested honestly",
"The habit that stuck and why",
"The habit that never stuck",
"Streaks and the tyranny of not breaking one",
"Missing a day and continuing anyway",
"Environment design instead of willpower",
"Removing friction versus adding motivation",
"The trigger that starts the behavior",
"Rewards you invented for yourself",
"Accountability, and whether it works for you",
"Telling people your goal, or not",
"Public commitment as a trap",
"The identity shift behind a habit",
"Being someone who does the thing versus doing the thing",
"Quitting something you were good at",
"The addiction nobody calls an addiction",
"Screens before bed and the honest attempt to stop",
"Mornings, and what they are actually for",
"Chronotypes and the schedules imposed on us",
"School start times, argued from experience",
"Working at night and the trade you make",
"Energy management instead of time management",
"The two good hours in your day",
"Protecting a block of time",
"Interruptions and their real cost",
"Context switching, measured",
"Deep work in a house with other people",
"Headphones as a signal",
"Noise, silence, and what you need to think",
"Working in public spaces",
"The desk setup that actually changed things",
"Standing, sitting, and the body at work",
"Wrist pain, eye strain, and the costs nobody budgets for",
"The break you do not take",
"Rest that is not scrolling",
"Boredom as an input",
"Anxiety, described without metaphor",
"The therapy conversation that shifted something",
"Naming a feeling accurately",
"Journaling as maintenance",
"The mood you can predict by the day of the week",
"Seasonal changes and your output",
"Winter, and what it does to you",
"Sunlight as a variable",
"The doctor's appointment you delayed",
"Advocating for yourself in a medical setting",
"Chronic anything and the invisibility of it",
"Caring for a body you did not choose",
"Medication and the conversation around it",
"Health advice on the internet",
"The wellness product you bought",
"Longevity culture, evaluated",
"Mortality at your current age",

/* ---------- place, time & home ---------- */
"The city you left and what you still defend about it",
"A place you loved that has changed",
"Returning somewhere after years",
"The neighborhood that raised you",
"Gentrification from the inside",
"Rent, and what it decides about your life",
"The apartment you could not afford and took anyway",
"Moving as an inventory of who you are",
"What you threw away and regret",
"The box you have not unpacked",
"Making a room feel like yours",
"The chair, the lamp, the specific object",
"Living with less on purpose",
"Living with more and being honest about it",
"Sharing space with people",
"Roommates and the systems that keep peace",
"Chores as a negotiation",
"The house rule that worked",
"Home as a feeling versus an address",
"The commute you had and what it did to you",
"Public transit as a shared civic space",
"Driving, and what you think about",
"The road trip and its enforced conversation",
"Travel that was not a vacation",
"The trip that went wrong",
"Traveling alone",
"Being a tourist without pretending otherwise",
"The place that was overrated and the one that was not",
"Learning a city by walking it",
"Getting lost on purpose",
"Language barriers and the kindness of strangers",
"Eating somewhere you could not read the menu",
"The souvenir that meant something",
"Photos from a trip you never look at",
"Coming home and the reentry",
"Living abroad and the version of you that exists there",
"Missing a place you have never lived",
"The landscape that recalibrates you",
"Water, mountains, or the specific terrain you need",
"Nature as a place you visit versus live in",
"Weather as a personality",
"The storm you remember",
"Seasons and how your year is actually structured",
"The month that is always hard",
"Anniversaries your body remembers",
"Time as measured by projects instead of dates",
"The year that felt long and the one that vanished",
"Keeping a calendar of what actually happened",
"Reading your own journal from three years ago",
"The version of you that wrote it",
"Future self as a stranger you make decisions for",
"Letters to yourself",
"Time capsules and what you would put in one",
"Predictions you made and got wrong",
"What you were sure would happen by now",
"The technology you expected that never arrived",
"The change you did not see coming",
"Nostalgia for a period you did not enjoy at the time",
"Documenting the ordinary",
"The photograph of a normal afternoon",
"What you will miss about right now",
"Aging, from where you stand",
"The birthday that landed differently",
"Milestones and the ages we assign them",
"Being ahead or behind an imaginary schedule",
"Comparison as a thief, examined honestly",
"The peer whose path you track",
"Watching someone succeed at what you wanted",
"Envy, described precisely",
"Admiration without envy",
"The person you were jealous of who was struggling",
"Success that looked different up close",
"The public life versus the private one",
"Ambition at different ages",
"What you would do with an unexpected free year",
"Sabbaticals for people who cannot take one",
"Doing nothing, badly",
"Waiting: for results, a reply, a diagnosis",
"Uncertainty as a permanent condition",
"Making decisions with incomplete information",
"Reversible versus irreversible choices",
"The decision you agonized over that did not matter",
"The one you made casually that changed everything",
"Regret, and whether it is useful",
"The path not taken, without romanticizing it",
"Counterfactuals and their limits",
"Being at peace with an old decision",
"Closing a chapter deliberately",
"Rituals for endings",
"The last time you did something without knowing it was the last",
"Firsts you remember and lasts you do not",
"Keeping something going past its natural end",
"Starting over in a new field",
"Being a beginner in public at any age",
"The thing you started this year",
"What you will still be doing in ten years",
"Legacy at a small scale",
"What you want people to be able to use after you",
"The archive you are leaving",
"Writing something your future family will read",
"Ordinary days as the actual life",

/* ---------- belief, self & meaning ---------- */
"The belief you changed your mind about this year",
"An opinion you hold that your friends do not",
"The thing you are wrong about, probably",
"How you decide what is true",
"Certainty as a warning sign",
"Doubt as a working method",
"The question you cannot answer and keep returning to",
"Faith, in whatever form you have it",
"Losing a belief and what replaced it",
"Ritual without religion",
"The practice that grounds you",
"Meaning made rather than found",
"Purpose as a construction project",
"The thing you do that has no justification",
"Play as an end in itself",
"Wasting time well",
"Optimization culture and what it costs",
"Measuring what matters and the parts that resist measurement",
"The unquantifiable thing you protect",
"Efficiency as a value with limits",
"Slowness on purpose",
"Doing something the hard way once",
"Manual processes worth keeping",
"Skills you keep because they are yours",
"Self-reliance and its limits",
"Asking for help as a value, not a failure",
"Independence as an inherited ideal",
"Interdependence, described concretely",
"Owing people and being owed",
"Responsibility to strangers",
"The civic duty you actually perform",
"Voting, jury duty, and the small machinery",
"Local politics as the level that touches you",
"The issue you changed your mind about",
"Talking politics with someone you love",
"Disagreement without contempt",
"The argument you regret winning",
"Being persuaded",
"What would change your mind, stated in advance",
"Principles versus preferences",
"The line you would not cross at work",
"Ethics in the small decisions",
"Honesty when it costs you something",
"The lie you told and its aftershocks",
"White lies and their accumulated weight",
"Integrity as consistency across rooms",
"Being the same person in every context",
"The version of you at work versus at home",
"Masks, code-switching, and what it takes",
"Authenticity as a demand",
"Privacy as a value in a public life",
"What you keep to yourself",
"The thing you have never written about",
"Secrets and their upkeep",
"Shame versus guilt, distinguished by example",
"Making amends concretely",
"Being disliked and surviving it",
"Caring less about opinions, in practice",
"Approval as a motivator you are unwinding",
"The compliment you cannot accept",
"Self-criticism and its diminishing returns",
"Talking to yourself the way you talk to a friend",
"Confidence built from evidence",
"Competence and the quiet it brings",
"The thing you are unreasonably good at",
"The thing you will never be good at",
"Accepting a ceiling",
"Effort versus talent, from experience",
"What ten thousand hours actually looked like",
"Motivation as a myth you stopped waiting for",
"Discipline as a set of systems, not a trait",
"Identity as the real lever",
"Changing a self-story",
"The label you dropped",
"Being defined by a role that ended",
"Reinvention without erasing the past",
"Continuity: what has stayed the same since you were ten",
"The child you were, still visible",
"Traits inherited and traits chosen",
"Nature, nurture, and the parts you can move",
"Free will as a practical question",
"Habit as character",
"The small daily thing that adds up to a life",
"What you do when nobody would know",
"Integrity in an empty room",
"Kindness that costs you something",
"Generosity as a practice with limits",
"Boundaries and the people who test them",
"Saying no as self-respect",
"The commitment you kept at real cost",
"Loyalty examined",
"Courage in an ordinary setting",
"The time you spoke up",
"The time you did not",
"Fear you acted through",
"Risk tolerance and where yours came from",
"Failure as information versus failure as identity",
"The worst outcome you survived",
"Hope as a discipline",
"What you are optimistic about, specifically",
"The future you are working toward, described in detail",

];

if (typeof module !== "undefined") {
  module.exports = TOPICS;
}
